### ISSUE TITLE
Error as loader is trying to resolve library's .babelrc

### ISSUE THREAD

**Issue by leesiongchan** [skorlir/ava-jspm-loader#4]
```
...babel-core/lib/transformation/file/options/option-manager.js:177
          throw new ReferenceError(messages.get("pluginUnknown", plugin, loc, i, dirname));
          ^

ReferenceError: Unknown plugin "syntax-jsx" specified in "/Volumes/.../jspm_packages/npm/@cycle/dom@12.0.3/.babelrc" at 0, attempted to resolve relative to "/Volumes/.../jspm_packages/npm/@cycle/dom@12.0.3"
```

**Comment by fluffywaffles** [comment]
I can't fix your issue given just what you've told me. Note that ava-jspm-loader is only tested with jspm v0.17.0 beta releases.

There are a couple places you can look.
1. This may be an issue in the way cycle-js is configured with jspm. You may be able to fix it with overrides.
2. You can re-run whatever command it was you were trying to issue when the error occurred, but prefix it with `AVA_JSPM_LOADER_DEBUG=1 <your command here>` and you'll get a bunch of output from the loader about its resolution process. This could give hints as to where exactly things are going wrong.

**Comment by leesiongchan** [comment]
Thank you @skorlir, I am using jspm 0.17 beta too, it seems a little verbose for the `AVA_JSPM_LOADER_DEBUG=1` and I can't see any useful information that might help. Anyway, I will let you know if I found anything new.
